name: Release plugin zip

on:
  push:
    tags:
      - "*beta*"

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build with Gradle
      run: ./gradlew buildPlugin -PpluginVersion=${{ github.ref_name }}

    - name: Press a release on GitHub with the downloadable .zip
      uses: ncipollo/release-action@v1
      with:
        draft: false
        allowUpdates: true
        artifacts: "build/distributions/*.zip"
        token: ${{ secrets.GITHUB_TOKEN }}

